blank_issues_enabled: true
contact_links:
  - name: Common Issues
    url: https://github.com/chaance/cla-assistant/blob/main/COMMON_ISSUES.md
    about: Please check for common issues and their solution here first before opening an issue.

